### ISSUE TITLE
importing OutlineExplorerWidget fails after update from 5.1.1 -> 5.1.5

### ISSUE THREAD

**Issue by cpascual** [spyder-ide/spyder#16808]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The following import used to work in 5.1.1 and fails with 5.1.5 :

`from spyder.plugins.outlineexplorer.widgets import OutlineExplorerWidget`

### What steps reproduce the problem?

1. upgrade spyder in conda from 5.1.1 to 5.1.5 (using conda-forge)
2. run `python3 -c  'from spyder.plugins.outlineexplorer.widgets import OutlineExplorerWidget'`

### What is the expected output? What do you see instead?

Expected: successful import

Got:
```
ImportError: cannot import name 'OutlineExplorerWidget' from 'spyder.plugins.outlineexplorer.widgets' 
```

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'OutlineExplorerWidget' from 'spyder.plugins.outlineexplorer.widgets' (/home/cpascual/miniconda3/envs/taurus/lib/python3.9/site-packages/spyder/plugins/outlineexplorer/widgets.py)
```

## Versions

* Spyder version:  5.1.5            py39hf3d152e_1    conda-forge
* Python version: 3.9.7           hb7a2778_3_cpython    conda-forg
* Qt version: 5.12.9               hda022c4_4    conda-forge
* PyQt version: 5.12.3           py39hf3d152e_7
* Operating System name/version: debian11 with conda

**Comment by ccordoba12** [comment]
Hey @cpascual, thanks for reporting. I don't know what is this exactly about, but we don't expect Spyder to be used as a library, so we can't promise (and never have done it) a stable API in its internal modules (even in minor releases). We only try to keep a stable API in `spyder.api` because we expect external developers use it to write third-party plugins, but that will only be the case when that module reaches its 1.0 version (probably in Spyder 6).

Now OutlineExplorerWidget is present in

https://github.com/spyder-ide/spyder/blob/v5.1.5/spyder/plugins/outlineexplorer/main_widget.py#L43

**Comment by cpascual** [comment]
Hi @ccordoba12 , thanks a lot for the answer and the clarification.

> I don't know what this is exactly about, but we don't expect Spyder to be used as a library, so we can't promise (and never have done it) a stable API in its internal modules (even in minor releases).

I was not aware of that. I was maintaining some inherited code that used this widget since spyer v2 or so and this explains why we had to track some API changes since then! ;-)

**Comment by ccordoba12** [comment]
Yeah, sorry about that! We've doing huge refactorings since Spyder 3 but (hopefully) most of them will be over in Spyder 6. The idea is for each plugin to at least have:

* `plugin.py`: where the plugin lives.
* `confpage.py`: its configuration page.
* `widgets/main_widget.py`: where its main widget lives (in case of dockable plugins).
* `container.py`: if the plugin is not dockable but provides graphical widgets.

Some plugins have `api.py` right now, but we're considering if it'd worth to keep those files, or expose its contents through `spyder.api`.
