### ISSUE TITLE
Spyder 2.2.1 does not work with Python < 2.7

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1497]
_From [lamego.p...@gmail.com](https://code.google.com/u/111970519697145467875/) on 2013-07-27T05:56:13Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. download spyder 2.1.1;
2. sudo python setup.py install
3. spyder What is the expected output? What do you see instead? The application should start What version of the product are you using? On what operating system? 2.2.1 on RHEL6 

Please provide any additional information below

. Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/spyderlib/spyder.py", line 2098, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python2.6/site-packages/spyderlib/spyder.py", line 1991, in run_spyder
    main = MainWindow(options)
  File "/usr/lib/python2.6/site-packages/spyderlib/spyder.py", line 381, in __init__
    title = "Spyder (Python &#37;s.&#37;s)" &#37; (sys.version_info.major,
AttributeError: 'tuple' object has no attribute 'major'

The named attributes were introduced on python 2.7: http://docs.python.org/2/library/sys.html#sys.version_info I have replaced .major and .minor with [0][1] and it's working fine now.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1497_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-09T12:55:42Z_

Ok, thanks a lot for the heads up! I'll fix it in our next release.

**Summary:** Spyder 2.2.1 does not work with Python &lt; 2.7  \<span class="oldvalue"> (was: Spyder 2.1.1 does not work with Python &lt; 2.7) \</span>

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-10T08:59:25Z_

Breaking compatibility with Python 2.5 and 2.6 seems like a critical bug that should require a maintenance release really soon.

**Status:** Accepted  
  **Owner:** ccordoba12  
  **Labels:** -Priority-High Priority-Critical MS-v2.2.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-10T09:06:13Z_

Yep, I'm preparing 2.2.2 right now (I'm almost have it finished).

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-10T09:22:29Z_

This issue was updated by revision e8517907aeeb .

**Status:** Fixed
