### ISSUE TITLE
matplotlib (v1.5.1) is not running inside of Spyder 2.3.6

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#2969]
## Description

**What steps will reproduce the problem?**

1. In Spyder 2.3.6 in Ubuntu 14.04.3 LTS running under Python 2.7, Matplotlib (v1.5.1)
   if you run '**import matplotlib.pyplot as plt**', then you will get the following errors:

**What is the expected output? What do you see instead?**
_Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 11, in <module>
    import matplotlib.cbook as cbook
AttributeError: 'module' object has no attribute 'cbook'_

**Please provide any additional information below**
This problem started occurring when I upgraded my MatplotLib from v1.4.3 to v1.5.1

## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 2.7.6
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Linux

## Optional dependencies
```
pyflakes >=0.5.0:  None (NOK)
pep8 >=0.6      :  None (NOK)
pygments >=1.6  :  1.6 (OK)
IPython >=1.0   :  None (NOK)
zmq >=2.1.11    :  14.0.1 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  None (NOK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.5.1 (OK)
pylint >=0.25   :  1.4.3 (OK)

```

**Comment by mvkrdndm** [comment]
did you tried to  import that code on idle , in  3.5 python did not give error

**Comment by s0r2637** [comment]
No. I imported inside Spyder 2.3.6 console.  Now I have reverted my
Matplotlib to 1.4.3, which seems to be stable.
The problem happened in import 'pyplot' from matplotlib.  The error happens
in the scientific_startup.py.

I can't test it anymore, as I have reverted to v1.4.3

Srini

**Comment by ccordoba12** [comment]
Please update to Spyder 2.3.8. I'm almost sure this issue was solved in that version.

**Comment by s0r2637** [comment]
Ok. I will try.

Srini

**Comment by s0r2637** [comment]
I tried.  Thanks it fixed the problem.

Srini

**Comment by ccordoba12** [comment]
Nice!! Closing this issue then ;-)

**Comment by xiayansuuny** [comment]
I have the same problem with you, but my Spyde Version is  2.3.6. how to solve it?
