### ISSUE TITLE
Internal error when opening spyder

### ISSUE THREAD

**Issue by b-fg** [spyder-ide/spyder#7406]
### What steps will reproduce the problem?

Every time I open spyder after upgrading to 3.3 I get this internal error message. Some other times Spyder cannot be opened at all and the application closes automatically.

### Traceback
```python-traceback
  File "/usr/local/lib/python3.5/dist-packages/spyder/app/mainwindow.py", line 1961, in valid_project
    if bool(self.projects.get_active_project_path()):
AttributeError: 'NoneType' object has no attribute 'get_active_project_path'
```

## Versions

* Spyder version: 3.3.0 
* Python version: 3.5.2
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Linux 4.4.0-130-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.5 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
psutil >=0.3      :  5.4.6 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.14.5 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
This is a duplicate of issue #7403.
