### PR TITLE
PR: Revert removing mamba from base environment specification

### LINKED ISSUE #24058: Error when updating to 6.05: 'libmambapy' has no attribute 'QueryFormat'
I've updated to 6.05 using the builtin updater of the standalone package on Ubuntu 24.04.

This error occured to me too after updating via the standalone installer:

```
Updating Spyder runtime environment...                                          
Traceback (most recent call last):                                              
  File "/home/user/.local/spyder-6/bin/mamba", line 7, in <module>             
    from mamba.mamba import main                                                
  File "/home/user/.local/spyder-6/lib/python3.11/site-packages/mamba/mamba.py", line 46, in <module>                                                          
    from mamba import repoquery as repoquery_api                                
  File "/home/user/.local/spyder-6/lib/python3.11/site-packages/mamba/repoquery.py", line 12, in <module>                                                      
    def _repoquery(query_type, q, pool, fmt=api.QueryFormat.JSON):              
                                            ^^^^^^^^^^^^^^^                     
AttributeError: module 'libmambapy' has no attribute 'QueryFormat'              
Cleaning packages and temporary files...                                        
Traceback (most recent call last):                                              
  File "/home/user/.local/spyder-6/bin/mamba", line 7, in <module>             
    from mamba.mamba import main                                                
  File "/home/user/.local/spyder-6/lib/python3.11/site-packages/mamba/mamba.py", line 46, in <module>
    from mamba import repoquery as repoquery_api
  File "/home/user/.local/spyder-6/lib/python3.11/site-packages/mamba/repoquery.py", line 12, in <module>
    def _repoquery(query_type, q, pool, fmt=api.QueryFormat.JSON):
                                            ^^^^^^^^^^^^^^^
AttributeError: module 'libmambapy' has no attribute 'QueryFormat'

```

when starting Spyder, the ipython console displays 

```
Traceback (most recent call last):
File "/home/user/.local/spyder𔂰/bin/mamba", line 7, in
from mamba.mamba import main
File "/home/user/.local/spyder𔂰/lib/python3.11/site‑packages/mamba/mamba.py", line 46, in
from mamba import repoquery as repoquery_api
File "/home/user/.local/spyder𔂰/lib/python3.11/site‑packages/mamba/repoquery.py", line 12, in
def _repoquery(query_type, q, pool, fmt=api.QueryFormat.JSON):
^^^^^^^^^^^^^^^
AttributeError: module 'libmambapy' has no attribute 'QueryFormat'
```

related: #24057

### PR DESCRIPTION
**Pull request by mrclary**
The conda-based installer base environment should not change primary dependencies for a minor/micro release.

Fixes #24058

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks @mrclary for finding a quick solution to this problem! I tested it manually and found there's an error that perhaps we should address in this PR too.

If the contents of a previous uncompressed conda-lock file are present in `get_temp_dir()/updates/X.X.X`, then a new conda-lock zip file for the same version is not uncompressed there. Instead, we use the currently available lock files.

It took me some time to realize that problem because I had the initial conda-lock files for 6.0.5 and 6.0.4 was picking up those files to perform the update (which, of course, gave me the error reported on issue #24058). After I manually removed `get_temp_dir()/updates/6.0.5`, then the update was performed successfully.

**Comment by mrclary** [comment]
> If the contents of a previous uncompressed conda-lock file are present in `get_temp_dir()/updates/X.X.X`, then a new conda-lock zip file for the same version is not uncompressed there. Instead, we use the currently available lock files.

This is not a bug, but a feature. The updater checks to see if it has already downloaded the update, so that it doesn't download again. If an error occurs during download, then the directory is cleaned so that a bad download is not kept.

However, the updater should probably _always_ get a new file size value. The updater uses this to validate the download. The "bad" 6.0.5 zip file and the "good" one are not likely to be exactly the same size, so the updater could then decide to re-download. In the future we should generate sha hashes for each artifact and use that to check for valid download rather than just the size; this may be more robust.

**Comment by ccordoba12** [comment]
> This is not a bug, but a feature. The updater checks to see if it has already downloaded the update, so that it doesn't download again. If an error occurs during download, then the directory is cleaned so that a bad download is not kept.

I agree that's a good feature when we're downloading the full installer because we don't want to redownload it again to perform the update. But since the conda-lock file is so small, I think we should remove/redownload it again to avoid an error like the one I was experiencing.

> However, the updater should probably always get a new file size value. The updater uses this to validate the download. The "bad" 6.0.5 zip file and the "good" one are not likely to be exactly the same size, so the updater could then decide to re-download

Ok, that's a good idea too.

So, do you prefer to leave that fix for another PR? Or include it in this one?

**Comment by mrclary** [comment]
> > However, the updater should probably always get a new file size value. The updater uses this to validate the download. The "bad" 6.0.5 zip file and the "good" one are not likely to be exactly the same size, so the updater could then decide to re-download
> 
> Ok, that's a good idea too.
> 
> So, do you prefer to leave that fix for another PR? Or include it in this one?

Let's leave it for another PR. Any users that experience the same problem you did will not see the fix anyway, until after 6.0.6. Additionally, always getting a new file size value will require a small refactor.

**Review by ccordoba12 — APPROVED** [review]
Thanks @mrclary!

**Comment by ccordoba12** [comment]
@meeseeksdev please backport to 6.x
