### ISSUE TITLE
matplotlib's Axes3D not working in ipython console on linux

### ISSUE THREAD

**Issue by niels-anders** [spyder-ide/spyder#2926]
## Description

The following lines: 

```python
import pylab as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
```

produce a 3D plot in spyder using the python console. However, the ipython console gives me:

```
AttributeError: 'module' object has no attribute '_string_to_bool' and no plot
```

I'm using linux mint 17.3 64-bit and python 2.7.6, the rest of the dependency version numbers are found below.

**What steps will reproduce the problem?**

1. ax = fig.add_subplot(111, projection='3d')
2. 
3. 

**What is the expected output? What do you see instead?**
expected output is a plot. Instead I receive an attribute error:  'module' object has no attribute '_string_to_bool'

**Please provide any additional information below**
it works fine on windows 10, spyder 2.3.8, matplotlib 1.5.1, ipython 4.0.1. I am not sure it is related to matplotlib 1.4 vs. 1.5, but when upgrading my linux's matplotlib to 1.5 the ipython kernel is not loading as described here: https://github.com/spyder-ide/spyder/issues/2793

it also works fine on my linux netbook 32-bit, spyder 3.0.0-dev, matplotlib 1.3.1, ipython 3.2.0
I can't reproduce it on another machine.

full error message is here:

```python-traceback
Traceback (most recent call last):

  File "<ipython-input-1-12e6a1cc5d11>", line 1, in <module>
    runfile('/home/niels/untitled0.py', wdir='/home/niels')

  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/home/niels/untitled0.py", line 12, in <module>
    ax = fig.add_subplot(111, projection='3d')

  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 964, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_subplots.py", line 78, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)

  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 91, in __init__
    *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 437, in __init__
    self.cla()

  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 1045, in cla
    Axes.cla(self)

  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 908, in cla
    self.grid(self._gridOn, which=rcParams['axes.grid.which'])

  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 1256, in grid
    self._draw_grid = maxes._string_to_bool(b)

AttributeError: 'module' object has no attribute '_string_to_bool'
```

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 2.7.6
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Linux

## Optional dependencies
```
pyflakes >=0.5.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  1.6 (OK)
IPython >=1.0      :  4.0.0 (OK)
zmq >=2.1.11       :  15.0.0 (OK)
qtconsole >=4.0    :  4.1.0 (OK)
pandas >=0.13.1    :  0.17.0 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
psutil >=0.3       :  3.2.2 (OK)
rope >=0.9.2       :  0.10.2 (OK)
jedi >=0.8.1;<0.9.0:  0.8.1 (OK)
matplotlib >=1.0   :  1.4.3 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
pylint >=0.25      :  1.4.4 (OK)

```

**Comment by ccordoba12** [comment]
I can reproduce the problem in Matplotlib version 1.4.3 but not in version 1.5.1. So please update to that version :-)
