### ISSUE TITLE
module 'clr' has no attribute 'AddReference' when running script multiple times

### ISSUE THREAD

**Issue by chagenvik** [spyder-ide/spyder#21802]
## Problem Description
After upgrading pythonnet from 2.5.2 to version 3.0.2 I get an error when running python code using the pythonnet package two times in a row. 

AttributeError: module 'clr' has no attribute 'AddReference'

If Kernel is restarted, I am able to run the script again, but the second time it crashes. 
I would prefer not to restart kernel every time I am going to run scripts. 

This was not an issue with pythonnet version 2.5.2, and started after I upgraded to 3.0.2. 

### What steps reproduce the problem?

1. Run the following lines of code in Spyder (Run file button, or F5):
```
#pythonnet module is imported as clr (see documentation https://github.com/pythonnet/pythonnet)
import clr
clr.AddReference("System")
```

2. Run it once more (without restarting kernel in the meantime)

### What is the expected output? What do you see instead?
To be able to run the code in Spyder with pythonnet version 3.0.2 without crash, and without having to restart kernel every time. 

### Paste Traceback/Error Below (if applicable)

My script "clr_spyder_bug.py"
```
#pythonnet module is imported as clr (https://github.com/pythonnet/pythonnet)
import clr
clr.AddReference("System")
```

Traceback:
```python-traceback
runfile('C:/Appl/clr_spyder_bug.py', wdir='C:/Appl')

runfile('C:/Appl/clr_spyder_bug.py', wdir='C:/Appl')
Reloaded modules: CLR, clr
Traceback (most recent call last):

  File C:\Appl\Python311\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\appl\clr_spyder_bug.py:9
    clr.AddReference("System")

AttributeError: module 'clr' has no attribute 'AddReference'

```

## Versions
* Spyder version: 5.5.0
* Python version: 3.11.7 (have tested on many different python versions as well, from 3.8 up to 3.11)
* Operating System name/version: Windows 10 Enterprise 22H2

### Dependencies
```
* pythonnet: 3.0.2
```

**Comment by ccordoba12** [comment]
Hey @chagenvik, thanks for reporting. It seems you need to add `clr` to the list of disabled modules from our User Module Reloader (UMR).

To do that, please to go the menu entry:

    Tools > Preferences

and select the section called `Python Interpreter`.

There you'll see a button named `Set UMR excluded (not reloaded) modules`, which you need to click and then add `clr` in the dialog that shows up afterwards.

Let us know if that works for you.

**Comment by chagenvik** [comment]
Thank you very much. It worked :)

**Comment by ZTnb** [comment]
I certainly install the clr module,but when I add clr in the dialog that shows up afterward,it shows that : The following modules are not installed on your machine.

**Comment by StevenGoode** [comment]
Yes, I have the same issue as ZTnb. Pythonnet is definitely installed on my machine. When I attempt to add clr or pythonnet to the list of UMR excluded modules, I receive a pop-up that says that the module (either clr or pythonnet) is not installed on my machine. Could this be because I installed pythonnet in an environment, as shown here for Spyder itself?: https://youtu.be/Ul79ihg41Rs
