### PR TITLE
PR: Add validation for conda version, raise error if using version <4.9 and if conda executable can't be detected (IPython Console)

### LINKED ISSUE #22554: Can not use Spyder 6 with old conda (4.8.3)
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

kernel doesn't open when using old version of conda (4.8.3, works with 4.9)

### What steps reproduce the problem?

1. Install Spyder 6 with conda 4.8.3
2. Try to use a kernel

### Paste Traceback/Error Below (if applicable)

```python-traceback

An error occurred while starting the kernel
usage: conda‑script.py [‑h] [‑V] command ...
conda‑script.py: error: unrecognized arguments: ‑‑no‑capture‑output
```

## Versions

* Spyder version: 6.0.0
* Python version: 3.14
* Qt version: 
* PyQt version: 
* Operating System name/version: windows

### LINKED ISSUE #23595: Kernel fails to start in Spyder 6 when conda distribution installation is in a custom path
Installed Spyder in new environment using conda. It installed v5.4.x and things worked fine. Couple days ago, saw a prompt to upgrade to v6.0.3. I followed the instructions and upgraded it. However, now I cannot start Spyder using the shortcut. Spyder IDE starts but fails to start the kernel. The option to restart kernel is also disabled. Starting from terminal works fine. However, I would still like to start using the shortcut.

How do I fix this?

Below is the error message in the IPYthon Console.

```
An error occurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\Users\testUser\.conda\envs\spyder‑env\Lib\site‑packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1719, in create_new_client
kernel_handler = self.get_cached_kernel(kernel_spec, cache=cache)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\testUser\.conda\envs\spyder‑env\Lib\site‑packages\spyder\plugins\ipythonconsole\widgets\mixins.py", line 59, in get_cached_kernel
new_kernel_handler = KernelHandler.new_from_spec(kernel_spec)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\testUser\.conda\envs\spyder‑env\Lib\site‑packages\spyder\plugins\ipythonconsole\utils\kernel_handler.py", line 393, in new_from_spec
kernel_manager.start_kernel(
File "C:\Users\testUser\.conda\envs\spyder‑env\Lib\site‑packages\jupyter_core\utils\__init__.py", line 165, in wrapped
return loop.run_until_complete(inner)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\testUser\.conda\envs\spyder‑env\Lib\asyncio\base_events.py", line 654, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "C:\Users\testUser\.conda\envs\spyder‑env\Lib\site‑packages\jupyter_client\manager.py", line 96, in wrapper
raise e
File "C:\Users\testUser\.conda\envs\spyder‑env\Lib\site‑packages\jupyter_client\manager.py", line 87, in wrapper
out = await method(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\testUser\.conda\envs\spyder‑env\Lib\site‑packages\jupyter_client\manager.py", line 435, in _async_start_kernel
kernel_cmd, kw = await self._async_pre_start_kernel(**kw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\testUser\.conda\envs\spyder‑env\Lib\site‑packages\jupyter_client\manager.py", line 400, in _async_pre_start_kernel
kw = await self.provisioner.pre_launch(**kw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\testUser\.conda\envs\spyder‑env\Lib\site‑packages\jupyter_client\provisioning\local_provisioner.py", line 198, in pre_launch
kernel_cmd = km.format_kernel_cmd(
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\testUser\.conda\envs\spyder‑env\Lib\site‑packages\jupyter_client\manager.py", line 307, in format_kernel_cmd
cmd = self.kernel_spec.argv + extra_arguments
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\testUser\.conda\envs\spyder‑env\Lib\site‑packages\spyder\plugins\ipythonconsole\utils\kernelspec.py", line 136, in argv
if conda_exe.endswith('micromamba'):
^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'
```

I tried changing the shortcut "target" to what it used to be prior to the upgrade with no success.
Shortcut Target after upgrade to v6.x
   ` C:\Users\testUser\.conda\envs\spyder-env\Scripts\spyder.exe "%1 "`

Shortcut target before upgrade
    `C:\apps\Miniconda3\v3_11_8_x64\Local\pythonw.exe C:\apps\Miniconda3\v3_11_8_x64\Local\cwp.py C:\Users\testUser\.conda\envs\spyder-env C:\Users\testUser\.conda\envs\spyder-env\pythonw.exe C:\Users\testUser\.conda\envs\spyder-env\Scripts\spyder-script.py`
 

Edit to add more info:
OS: Windows 10
Relevant packages:
```
spyder                    6.0.3 
spyder-kernels            3.0.2 
ipython                   8.31.0
```

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

Validate conda version and raise an error as needed. See https://github.com/spyder-ide/spyder/issues/22554#issuecomment-2691844623

A preview of the messages:

image
image

### Issue(s) Resolved

Fixes #23595
Fixes #22554 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Review by ccordoba12 — COMMENTED** [review]
Although marked as draft, I took the opportunity to leave you an early review for you @dalthviz.

File: spyder/plugins/ipythonconsole/utils/kernelspec.py [hunk 1]
```diff
@@ -9,6 +9,7 @@
 """
 
 # Standard library imports
+from packaging.version import parse
```
Comment (ccordoba12) [inline spyder/plugins/ipythonconsole/utils/kernelspec.py:12]: `packaging` is not a standard library module. So, please move this import to the third-party section-

File: spyder/plugins/ipythonconsole/utils/kernelspec.py [hunk 2]
```diff
@@ -125,6 +126,17 @@ def argv(self):
             # If executable is a conda environment, use "run" subcommand to
             # activate it and run spyder-kernels.
             conda_exe = find_conda()
+            if not conda_exe:
+                # Raise error since we were unable to determine the path to
+                # the conda executable (e.g conda was installed in a
+                # non-standard location).
```
Comment (ccordoba12) [inline spyder/plugins/ipythonconsole/utils/kernelspec.py:132]:
```suggestion
                # the conda executable (e.g when Anaconda/Miniconda was
                # installed in a non-standard location).
```

Improve comment a bit.

File: spyder/plugins/ipythonconsole/utils/kernelspec.py [hunk 3]
```diff
@@ -125,6 +126,17 @@ def argv(self):
...
+                # See spyder-ide/spyder#23595
+                raise SpyderKernelError(
+                    _("Unable to determine path to conda executable. "
+                      "Please add the path to the conda executable to your "
+                      "PATH environment variable for it to be detected.")
```
Comment (ccordoba12) [inline spyder/plugins/ipythonconsole/utils/kernelspec.py:137]:
```suggestion
                    _(
                        "Spyder couldn't find conda or mamba in your system "
                        "to activate the kernel's environment. Please add the "
                        "directory where the conda or mamba executable is "
                        "located to your PATH environment variable for it to "
                        "be detected."
                    )
```

Improve message a bit.

File: spyder/plugins/ipythonconsole/utils/kernelspec.py [hunk 4]
```diff
@@ -138,10 +150,23 @@ def argv(self):
...
+                # Raise error since an unsupported conda version is being used
+                # (conda<4.9).
+                # See spyder-ide/spyder#22554
+                raise SpyderKernelError(
+                    _(
+                        "The detected version of Conda is too old and not "
+                        "supported by Spyder. The minimum supported version is "
+                        "4.9 and currently you have {conda_version}.<br><br>."
+                        "<b>Note</b>: You need to update restart Spyder after "
+                        "updating Conda for the change to take effect."
```
Comment (ccordoba12) [inline spyder/plugins/ipythonconsole/utils/kernelspec.py:167]:
```suggestion
                        "<b>Note</b>: You need to restart Spyder after "
                        "updating Conda for the change to take effect."
```

Fix error in my previous suggestion.

**Review by ccordoba12 — COMMENTED** [review]
Last comments/suggestion for you @dalthviz, then this should be ready.

**Review by ccordoba12 — APPROVED** [review]
Looks good to me now, thanks @dalthviz!

**Comment by ccordoba12** [comment]
@meeseeksdev please backport to 6.x
