### ISSUE TITLE
IPython console does not link to the file and row that caused the error anymore

### ISSUE THREAD

**Issue by Illviljan** [spyder-ide/spyder#20407]
## Problem Description
IPython console does not link to the file and row that caused the error anymore in spyder 5.4.2. 
It worked fine in 5.4.0.

### What steps reproduce the problem?
Create a script:
```python
import numpy as np


a = np.arrayy([1, 2, 3])
```
Run the script

```python
runfile('C:/Projects/Python/Scripts/Misc/spyder_no_error_linking.py', wdir='C:/Projects/Python/Scripts/Misc')
Traceback (most recent call last):

  File ~\AppData\Local\miniconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\projects\python\scripts\misc\spyder_no_error_linking.py:4
    a = np.arrayy([1, 2, 3])

  File ~\AppData\Local\miniconda3\lib\site-packages\numpy\__init__.py:311 in __getattr__
    raise AttributeError("module {!r} has no attribute "

AttributeError: module 'numpy' has no attribute 'arrayy'
```
You should be able to click on 
```python
  File ~\AppData\Local\miniconda3\lib\site-packages\numpy\__init__.py:311 in __getattr__
```
And get to that file and row, this works in 5.4.0.

## Versions

* Spyder version: 5.4.2  (conda)
* Python version: 3.9.15 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows 10

**Comment by dalthviz** [comment]
Hi @Illviljan thank you for the feedback! I was able to reproduce this, we will check for a fix for it in a future release :+1:

@ccordoba12 maybe this is caused due to the update to IPython 8.x?

**Comment by ccordoba12** [comment]
> @ccordoba12 maybe this is caused due to the update to IPython 8.x?

Yes, it is and I can reproduce it too. I'll take care of it in our next version (5.4.3), to be released in March.
