### PR TITLE
PR:Add missing sig prefix to signal call.

### PR DESCRIPTION
**Pull request by rlaverde**
After merging #4535 with master, this line cause an error

```
  File "/home/rlaverde/code/spyder/spyder/plugins/editor.py", line 590, in visibility_changed
    self.update_plugin_title.emit()
AttributeError: 'function' object has no attribute 'emit'
```

### CODE REVIEW

**Comment by ccordoba12** [comment]
This is already fixed.

**Comment by rlaverde** [comment]
Yes, I didn't see #4540 😞
