### ISSUE TITLE
rtree dependency error 

### ISSUE THREAD

**Issue by ThiPv** [spyder-ide/spyder#15185]
Like other issues reported complaining about spyder-kernels error on startup I receive this message:

```
You have missing dependencies!

# Mandatory:
rtree >=0.8.3 : None (NOK)
spyder-kernels >=2.0.1,<2.1.0 : 2.0.1 (NOK)

Please install them to avoid this message.
```
Below the conda list command filtering these packages.

```
(myenv) PS C:\Users\EPEV> conda list | Select-String -Pattern "rtree|^spyder"

rtree                     0.9.7            py38h8b54edf_1    conda-forge
spyder                    5.0.0            py38haa244fe_0    conda-forge
spyder-kernels            2.0.1            py38haa244fe_0    conda-forge
```

**Comment by lindnemi** [comment]
I have a very similar error, where spyder is asking for `spyder_kernels` (with `_` instead of `-`).

**Comment by 93chanle** [comment]
I also have the exact error. Looking forward for any support. Thank you!

**Comment by raphaelquast** [comment]
same here... all dependencies fulfilled but spider 5 is complaining about missing the aforementioned dependencies

**Comment by sweettyler** [comment]
This is a bug in Python 3.8.8, and has nothing to do with Spyder. Try "import rtree" and see what happens.

**Comment by raphaelquast** [comment]
... I'm not sure it has something to do with python 3.8.8 since I'm getting the same error in python 3.7.10

however, you are right, `import rtree` fails with the following error:

```python
OSError: could not find or load spatialindex_c-64.dll
```

**Comment by sweettyler** [comment]
@raphaelquast you are on windows so the error is different from mine. on Linux if I roll back Python from 3.8.8 to 3.8.5 then everything is fine. Also reported the same thing to rtree. see https://github.com/Toblerity/rtree/issues/182.

**Comment by ccordoba12** [comment]
I wonder if this is a compilation error in Conda-forge and not something directly related to rtree.

@sweettyler, what rtree version are you using in Python 3.8.5?

**Comment by sweettyler** [comment]
@ccordoba12 I have never upgrade or downgrade rtree. it is v0.9.4 as shown below:

# Name                    Version                   Build  Channel
rtree                     0.9.4                    py38_1  

The only difference is Python 3.8.5 or Python 3.8.8 and with the Python 3.8.8 I cannot import retree.

**Comment by ccordoba12** [comment]
As @sweettyler mentioned, this is caused by an installation issue with Python 3.8.8. So for now the only advice we can give you is not use that version.

Other than that, there's nothing else we can do to help you with this problem, sorry.

**Comment by sweettyler** [comment]
@ccordoba12 Anaconda released another version python 3.8.8 two days ago and this new version fixed the rtree bug.

**Comment by ccordoba12** [comment]
Good to know! Thanks for letting us know about it @sweettyler.

**Comment by charliedives** [comment]
Thank you so much....I'm a newbie and I was going crazy trying to get Spyder working after upgrading to v5....which must have brought Python 3.8.8 along for the ride
