### ISSUE TITLE
Spyder stopped working with Qt4.6

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2083]
_From [Eric.Fre...@gmail.com](https://code.google.com/u/107162932778938309627/) on 2014-12-11T11:15:54Z_

The work going on in the master branch to use newstyle signals / slots has caused Spyder to not launch on RHEL6 which uses Qt4.6.
This is because the directoryLoaded signal on QFileSystemModel was introduced in Qt4.7.
With the old style signals on Qt4.6 this signal would never be emitted... but with the newstyle signals it cannot make the connection and Spyder errors out before starting up.

Should either fix this or update the requirements.
Currently the requirements list PyQt4.6 but do not mention the underlying Qt requirement.
I can confirm that Spyder launches on 4.8, I don't have a 4.7 system to test on.

  File "/home/eric/dev/spyder/spyderlib/widgets/explorer.py", line 120, in setup_view
    self.fsmodel.directoryLoaded.connect(
AttributeError: 'QFileSystemModel' object has no attribute 'directoryLoaded'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2083_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-12T13:55:07Z_

Thanks for reporting. I'll fix it so that Spyder keeps working on RedHat/CentOS.

**Summary:** Spyder stopped working with Qt4.6  \<span class="oldvalue"> (was: 2.3.2 works with Qt4.6, master requires at least 4.7) \</span>  
  **Labels:** MS-v2.4 Cat-SpyderGUI

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-17T13:51:51Z_

This issue was closed by revision 5f34c0a48072 .

**Status:** Fixed
