### ISSUE TITLE
can't import hashtable

### ISSUE THREAD

**Issue by zzd1992** [spyder-ide/spyder#4205]
I work in ubuntu 14.04.
I update Spyder use the following command:
> sudo pip install --upgrade spyder

The updating looks successful. But it can't start. (I also have tried the reset command).
And the error is "cannot import name hashtable".
And here is the **Traceback**:

> File "/usr/local/lib/python2.7/dist-packages/spyder/app/mainwindow.py", line 2999, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/local/lib/python2.7/dist-packages/spyder/app/mainwindow.py", line 2901, in run_spyder
    main.setup()
  File "/usr/local/lib/python2.7/dist-packages/spyder/app/mainwindow.py", line 824, in setup
    self.findinfiles = FindInFiles(self)
  File "/usr/local/lib/python2.7/dist-packages/spyder/plugins/findinfiles.py", line 52, in __init__
    include = self.include_patterns()
  File "/usr/local/lib/python2.7/dist-packages/spyder/plugins/findinfiles.py", line 105, in include_patterns
    for ext in get_edit_extensions():
  File "/usr/local/lib/python2.7/dist-packages/spyder/config/utils.py", line 140, in get_edit_extensions
    edit_filetypes = get_edit_filetypes()
  File "/usr/local/lib/python2.7/dist-packages/spyder/config/utils.py", line 118, in get_edit_filetypes
    pygments_exts = _get_pygments_extensions()
  File "/usr/local/lib/python2.7/dist-packages/spyder/config/utils.py", line 85, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "/usr/local/lib/python2.7/dist-packages/pygments/plugin.py", line 52, in find_plugin_lexers
    for entrypoint in iter_entry_points(LEXER_ENTRY_POINT):
  File "/usr/local/lib/python2.7/dist-packages/pygments/plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

How to solve it?

**Comment by ccordoba12** [comment]
Please try

    sudo pip install -U setuptools

to see if that fixes the problem.

**Comment by zzd1992** [comment]
I solved it.
The version of packaging module is too high.
I just change line **59** in file **/usr/local/lib/python2.7/dist-packages/packaging/requirements.py**
> MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")

into the following
> MARKER_EXPR = originalTextFor(MARKER_EXPR)("marker")

See a similar problem in webpage [](https://bugs.centos.org/view.php?id=12722)
