### ISSUE TITLE
AttributeError in Profiler if kernel fails to start

### ISSUE THREAD

**Issue by andres-ytree** [spyder-ide/spyder#25327]
### What steps will reproduce the problem?

Opened Spyder and encountered the error. Took no other actions other than opening Spyder via Anaconda Navigator after updating Anaconda Navigator to 2.7.0

### Traceback
```python-traceback
Traceback (most recent call last):

  File "/opt/anaconda3/envs/python3-13/lib/python3.13/site-packages/spyder/plugins/profiler/widgets/main_widget.py", line 724, in _on_kernel_ready
    self._stop_profiling()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/anaconda3/envs/python3-13/lib/python3.13/site-packages/spyder/plugins/profiler/widgets/main_widget.py", line 546, in _stop_profiling
    if widget.is_profiling:
       ^^^^^^^^^^^^^^^^^^^
AttributeError: '_ErroredMessageWidget' object has no attribute 'is_profiling'
```

## Versions

* Spyder version: 6.1.0  (conda)
* Python version: 3.13.3 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: macOS-26.0.1-arm64-arm-64bit-Mach-O

### Dependencies

```
# Mandatory:
aiohttp >=3.11.2                                                  :  3.11.10 (OK)
applaunchservices >=0.3.0                                         :  0.3.0 (OK)
asyncssh >=2.14.0,<3.0.0                                          :  2.17.0 (OK)
atomicwrites >=1.2.0                                              :  1.4.0 (OK)
bcrypt >=4.3.0                                                    :  4.3.0 (OK)
chardet >=2.0.0                                                   :  4.0.0 (OK)
cloudpickle >=0.5.0                                               :  3.0.0 (OK)
cookiecutter >=1.6.0                                              :  1.7.3 (OK)
diff_match_patch >=20181111                                       :  20200713 (OK)
github >=2.3.0                                                    :  2.4.0 (OK)
importlib_metadata >=4.6.0                                        :  8.5.0 (OK)
intervaltree >=3.0.2                                              :  3.1.0 (OK)
IPython >=8.15.0,<10.0.0,!=8.17.1,!=9.1.0,!=9.2.0,!=9.3.0,!=9.4.0 :  8.30.0 (OK)
ipython_pygments_lexers >=1.0                                     :  1.1.1 (OK)
jedi >=0.17.2,<0.20.0                                             :  0.19.2 (OK)
jellyfish >=0.7                                                   :  1.1.3 (OK)
jsonschema >=3.2.0                                                :  4.23.0 (OK)
keyring >=17.0.0                                                  :  24.3.1 (OK)
nbconvert >=4.0                                                   :  7.16.6 (OK)
numpydoc >=0.6.0                                                  :  1.2 (OK)
packaging >=20.0                                                  :  24.2 (OK)
parso >=0.7.0,<0.9.0                                              :  0.8.4 (OK)
pexpect >=4.4.0                                                   :  4.8.0 (OK)
pickleshare >=0.4                                                 :  0.7.5 (OK)
psutil >=5.3                                                      :  5.9.0 (OK)
pygments >=2.0                                                    :  2.19.1 (OK)
pylint >=3.1,<4                                                   :  3.3.5 (OK)
pylint_venv >=3.0.2                                               :  3.0.3 (OK)
pyls_spyder >=0.4.0                                               :  0.4.0 (OK)
pylsp >=1.13.0,<1.14.0                                            :  1.13.1 (OK)
pylsp_black >=2.0.0,<3.0.0                                        :  2.0.0 (OK)
pylsp_ruff >=2.3.0,<3.0.0                                         :  2.3.0 (OK)
pyuca >=1.2                                                       :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0                                         :  3.2.3 (OK)
qstylizer >=0.2.2                                                 :  0.2.2 (OK)
qtawesome >=1.4.0,<1.5.0                                          :  1.4.0 (OK)
qtconsole >=5.7.0,<5.8.0                                          :  5.7.0 (OK)
qtpy >=2.4.0                                                      :  2.4.1 (OK)
rtree >=0.9.7                                                     :  1.0.1 (OK)
sphinx >=0.6.6                                                    :  8.2.3 (OK)
spyder_kernels >=3.1.0,<3.2.0                                     :  3.1.1 (OK)
superqt >=0.6.2,<1.0.0                                            :  0.7.3 (OK)
textdistance >=4.2.0                                              :  4.2.1 (OK)
three_merge >=0.1.1                                               :  0.1.1 (OK)
watchdog >=0.10.3                                                 :  4.0.2 (OK)
yarl >=1.9.4                                                      :  1.18.0 (OK)
zmq >=24.0.0                                                      :  26.2.0 (OK)

# Optional:
cython >=0.21                                                     :  None (NOK)
matplotlib >=3.0.0                                                :  3.10.1 (OK)
numpy >=1.7                                                       :  2.3.0 (OK)
pandas >=1.1.1                                                    :  2.2.3 (OK)
scipy >=0.17.0                                                    :  1.15.2 (OK)
sympy >=0.7.3                                                     :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at /opt/anaconda3/envs/python3-13:
#
# Name                    Version                   Build  Channel
aiohappyeyeballs          2.4.4           py313hca03da5_0  
aiohttp                   3.11.10         py313h80987f9_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
alabaster                 0.7.16          py313hca03da5_0  
altair                    5.5.0                    pypi_0    pypi
applaunchservices         0.3.0           py313hca03da5_0  
appnope                   0.1.3           py313hca03da5_0  
appscript                 1.3.0           py313h80987f9_0  
arrow                     1.3.0           py313hca03da5_0  
arrow-cpp                 19.0.0               h0b7d223_2  
astroid                   3.3.8           py313hca03da5_0  
asttokens                 3.0.0           py313hca03da5_0  
asyncssh                  2.17.0          py313hca03da5_0  
atomicwrites              1.4.0                      py_0  
attrs                     24.3.0          py313hca03da5_0  
autopep8                  2.0.4              pyhd3eb1b0_0  
aws-c-auth                0.6.19               h80987f9_0  
aws-c-cal                 0.5.20               h80987f9_0  
aws-c-common              0.8.5                h80987f9_0  
aws-c-compression         0.2.16               h80987f9_0  
aws-c-event-stream        0.2.15               h313beb8_0  
aws-c-http                0.6.25               h80987f9_0  
aws-c-io                  0.13.10              h80987f9_0  
aws-c-mqtt                0.7.13               h80987f9_0  
aws-c-s3                  0.1.51               h80987f9_0  
aws-c-sdkutils            0.1.6                h80987f9_0  
aws-checksums             0.1.13               h80987f9_0  
aws-crt-cpp               0.18.16              h313beb8_0  
aws-sdk-cpp               1.11.212             hdd7fb2f_0  
babel                     2.16.0          py313hca03da5_0  
bcrypt                    4.3.0           py313h2aea54e_0  
beautifulsoup4            4.12.3          py313hca03da5_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     25.1.0                   pypi_0    pypi
blas                      1.0                    openblas  
bleach                    6.2.0           py313hca03da5_0  
blinker                   1.9.0                    pypi_0    pypi
boost-cpp                 1.82.0               h48ca7d4_2  
bottleneck                1.4.2           py313ha35b7ea_0  
brotli-python             1.0.9           py313h313beb8_9  
bzip2                     1.0.8                h80987f9_6  
c-ares                    1.19.1               h80987f9_0  
ca-certificates           2025.11.4            hca03da5_0  
ca-certificates-cos6-x86_64 2016.2.10            h4d6d018_0  
cachetools                5.5.2                    pypi_0    pypi
cattrs                    24.1.2          py313hca03da5_0  
certifi                   2025.10.5       py313hca03da5_0  
cffi                      1.17.1          py313h3eb5a62_1  
cfgv                      3.4.0           py313hca03da5_0  
chardet                   4.0.0           py313hca03da5_1003  
charset-normalizer        3.4.2                    pypi_0    pypi
choreographer             1.1.1                    pypi_0    pypi
clarabel                  0.10.0                   pypi_0    pypi
click                     8.1.8           py313hca03da5_0  
cloudpickle               3.0.0           py313hca03da5_0  
comm                      0.2.1           py313hca03da5_0  
contourpy                 1.3.1           py313h48ca7d4_0  
cookiecutter              1.7.3              pyhd3eb1b0_0  
copy-jdk-configs-cos6-x86_64 3.3                           4  
cryptography              44.0.1          py313h8026fc7_0  
curl-cffi                 0.10.0                   pypi_0    pypi
cvxpy                     1.7.1                    pypi_0    pypi
cycler                    0.11.0             pyhd3eb1b0_0  
cyrus-sasl                2.1.28               h9131b1a_1  
databricks                0.2                      pypi_0    pypi
databricks-bridge         0.0.7                    pypi_0    pypi
databricks-cli            0.18.0                   pypi_0    pypi
databricks-sql-connector  4.0.3                    pypi_0    pypi
debugpy                   1.8.11          py313h313beb8_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
deprecated                1.2.13          py313hca03da5_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.8           py313hca03da5_0  
distlib                   0.3.8           py313hca03da5_0  
docstring-to-markdown     0.11            py313hca03da5_0  
docutils                  0.21.2          py313hca03da5_0  
ecos                      2.0.14          py313ha35b7ea_0  
ecs-logging               2.2.0                    pypi_0    pypi
elastic-apm               6.23.0                   pypi_0    pypi
et-xmlfile                2.0.0                    pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.7.1                h313beb8_0  
filelock                  3.17.0          py313hca03da5_0  
flake8                    7.2.0                    pypi_0    pypi
fonttools                 4.55.3          py313h80987f9_0  
freetype                  2.13.3               h47d26ad_0  
frozendict                2.4.6                    pypi_0    pypi
frozenlist                1.5.0           py313h80987f9_0  
fzf                       0.55.0               hf59b786_0  
gconf2-cos6-x86_64        2.28.0                        4  
gettext                   0.21.0               hbdbcc25_2  
gflags                    2.2.2                h313beb8_1  
gitdb                     4.0.12                   pypi_0    pypi
gitpython                 3.1.45                   pypi_0    pypi
glib                      2.78.4               h313beb8_0  
glib-tools                2.78.4               h313beb8_0  
glog                      0.5.0                h313beb8_1  
google-api-core           2.25.1                   pypi_0    pypi
google-api-python-client  2.175.0                  pypi_0    pypi
google-auth               2.40.3                   pypi_0    pypi
google-auth-httplib2      0.2.0                    pypi_0    pypi
google-auth-oauthlib      1.2.2                    pypi_0    pypi
googleapis-common-protos  1.70.0                   pypi_0    pypi
gspread                   6.2.1                    pypi_0    pypi
gst-plugins-base          1.14.1               h313beb8_1  
gstreamer                 1.14.1               h80987f9_1  
holidays                  0.71                     pypi_0    pypi
httplib2                  0.22.0                   pypi_0    pypi
icu                       73.1                 h313beb8_0  
identify                  2.5.5           py313hca03da5_0  
idna                      3.10                     pypi_0    pypi
imagesize                 1.4.1           py313hca03da5_0  
importlib-metadata        8.5.0           py313hca03da5_0  
inflection                0.5.1           py313hca03da5_1  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.29.5          py313hca03da5_1  
ipython                   8.30.0          py313hca03da5_0  
ipython_pygments_lexers   1.1.1           py313hca03da5_0  
isort                     6.0.1           py313hca03da5_0  
jaraco.classes            3.2.1              pyhd3eb1b0_0  
java-1.7.0-openjdk-cos6-x86_64 1.7.0.131            haf0aaab_0  
jedi                      0.19.2          py313hca03da5_0  
jellyfish                 1.1.3           py313h1bd1ac0_0  
jinja2                    3.1.6           py313hca03da5_0  
jinja2-time               0.2.0              pyhd3eb1b0_3  
joblib                    1.4.2                    pypi_0    pypi
jpackage-utils-cos6-x86_64 1.7.5                         4  
jpeg                      9e                   h80987f9_3  
jsonschema                4.23.0          py313hca03da5_0  
jsonschema-specifications 2023.7.1        py313hca03da5_0  
jupyter_client            8.6.3           py313hca03da5_0  
jupyter_core              5.7.2           py313hca03da5_0  
jupyterlab_pygments       0.3.0           py313hca03da5_0  
kaleido                   1.1.0                    pypi_0    pypi
keyring                   24.3.1          py313hca03da5_0  
kiwisolver                1.4.8           py313h313beb8_0  
krb5                      1.20.1               hf3e1bf2_1  
lcms2                     2.16                 he26ebf3_1  
lerc                      4.0.0                h313beb8_0  
libabseil                 20250127.0      cxx17_h313beb8_0  
libboost                  1.82.0               h0bc93f9_2  
libbrotlicommon           1.0.9                h80987f9_9  
libbrotlidec              1.0.9                h80987f9_9  
libbrotlienc              1.0.9                h80987f9_9  
libclang                  14.0.6          default_h1b80db6_2  
libclang13                14.0.6          default_h24352ff_2  
libcurl                   8.12.1               hde089ae_0  
libcxx                    20.1.6               ha82da77_0    conda-forge
libdeflate                1.22                 h80987f9_0  
libedit                   3.1.20230828         h80987f9_0  
libev                     4.33                 h1a28f6b_1  
libevent                  2.1.12               h02f6b3c_1  
libffi                    3.4.4                hca03da5_1  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libglib                   2.78.4               h0a96307_0  
libgrpc                   1.71.0               h62f6fdd_0  
libiconv                  1.16                 h80987f9_3  
libjpeg-turbo-cos6-x86_64 1.2.1                         4  
libllvm14                 14.0.6               h19fdd8a_4  
libmpdec                  4.0.0                h80987f9_0  
libnghttp2                1.57.0               h62f6fdd_0  
libopenblas               0.3.21               h269037a_0  
libpng                    1.6.39               h80987f9_0  
libpq                     17.4                 h02f6b3c_0  
libprotobuf               5.29.3               h9f9f828_0  
libre2-11                 2024.07.02           h313beb8_0  
libsodium                 1.0.18               h1a28f6b_0  
libspatialindex           1.9.3                hc377ac9_0  
libssh2                   1.11.1               h3e2b118_0  
libthrift                 0.15.0               h73c2103_2  
libtiff                   4.7.0                h91aec0a_0  
libwebp-base              1.3.2                h80987f9_1  
libxml2                   2.13.7               h0b34f26_0  
libxslt                   1.1.41               hf4d3faa_0  
libzlib                   1.2.13               hfb2fe0b_6    conda-forge
llvm-openmp               14.0.6               hc6e5704_0  
logistro                  1.1.0                    pypi_0    pypi
lsprotocol                2025.0.0        py313hca03da5_0  
lxml                      5.3.0           py313h1d4350b_1  
lz4                       4.4.4                    pypi_0    pypi
lz4-c                     1.9.4                h313beb8_1  
markupsafe                3.0.2           py313h80987f9_0  
matplotlib                3.10.1                   pypi_0    pypi
matplotlib-inline         0.1.6           py313hca03da5_0  
mccabe                    0.7.0              pyhd3eb1b0_0  
mistune                   3.1.2           py313hca03da5_0  
more-itertools            10.3.0          py313hca03da5_0  
multidict                 6.1.0           py313h80987f9_0  
multitasking              0.0.11                   pypi_0    pypi
mypy_extensions           1.0.0           py313hca03da5_0  
mysql                     8.4.0                h065ec36_2  
narwhals                  2.6.0                    pypi_0    pypi
nbclient                  0.10.2          py313hca03da5_0  
nbconvert                 7.16.6          py313hca03da5_0  
nbconvert-core            7.16.6          py313hca03da5_0  
nbconvert-pandoc          7.16.6          py313hca03da5_0  
nbformat                  5.10.4          py313hca03da5_0  
ncurses                   6.4                  h313beb8_0  
nest-asyncio              1.6.0           py313hca03da5_0  
nodeenv                   1.9.1           py313hca03da5_0  
numexpr                   2.10.1          py313h5d9532f_0  
numpy                     2.3.0                    pypi_0    pypi
numpydoc                  1.2                pyhd3eb1b0_0  
oauth2client              4.1.3                    pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openjdk                   22.0.1               hbeb2e11_0    conda-forge
openjpeg                  2.5.2                hba36e21_1  
openldap                  2.6.4                he7ef289_0  
openpyxl                  3.1.5           py313h80987f9_1  
openssl                   3.5.0                h81ee809_1    conda-forge
orc                       2.1.1                h55d209b_0  
orjson                    3.11.3                   pypi_0    pypi
osqp                      1.0.3                    pypi_0    pypi
p11-kit-cos6-x86_64       0.18.5                        4  
p11-kit-trust-cos6-x86_64 0.18.5                        4  
packaging                 24.2            py313hca03da5_0  
pandas                    2.2.3           py313hcf29cfe_0  
pandoc                    2.12                 hca03da5_3  
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.4           py313hca03da5_0  
pathspec                  0.10.3          py313hca03da5_0  
pcre2                     10.42                hb066dcc_1  
peewee                    3.17.9                   pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    11.1.0          py313h41ba818_1  
pip                       24.2            py313hca03da5_0  
platformdirs              4.3.7           py313hca03da5_0  
plotly                    5.24.1          py313h7eb115d_1  
pluggy                    1.5.0           py313hca03da5_0  
ply                       3.11            py313hca03da5_1  
poyo                      0.5.0              pyhd3eb1b0_0  
pre-commit                4.2.0                    pypi_0    pypi
prompt-toolkit            3.0.43          py313hca03da5_0  
prompt_toolkit            3.0.43               hd3eb1b0_0  
propcache                 0.3.1           py313h80987f9_0  
proto-plus                1.26.1                   pypi_0    pypi
protobuf                  6.31.1                   pypi_0    pypi
psutil                    5.9.0           py313h80987f9_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py4j                      0.10.9.9                 pypi_0    pypi
pyarrow                   19.0.0          py313h313beb8_1  
pyasn1                    0.6.1                    pypi_0    pypi
pyasn1-modules            0.4.2                    pypi_0    pypi
pycodestyle               2.13.0                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pydeck                    0.9.1                    pypi_0    pypi
pydocstyle                6.3.0           py313hca03da5_0  
pyflakes                  3.3.2                    pypi_0    pypi
pygithub                  2.4.0           py313hca03da5_0  
pygments                  2.19.1          py313hca03da5_0  
pyjwt                     2.10.1          py313hca03da5_0  
pylint                    3.3.5           py313hca03da5_0  
pylint-venv               3.0.3           py313hca03da5_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pynacl                    1.5.0           py313h80987f9_1  
pyobjc-core               10.1            py313h80987f9_0  
pyobjc-framework-cocoa    10.1            py313hb094c41_0  
pyobjc-framework-coreservices 10.1            py313hdd8dd1f_0  
pyobjc-framework-fsevents 10.1            py313hca03da5_0  
pyparsing                 3.2.0           py313hca03da5_0  
pyqt                      5.15.10         py313h313beb8_1  
pyqt5-sip                 12.13.0         py313h80987f9_1  
pyqtwebengine             5.15.10         py313h313beb8_1  
pyscipopt                 5.5.0                    pypi_0    pypi
pysocks                   1.7.1           py313hca03da5_0  
pyspark                   3.5.5                    pypi_0    pypi
pytest                    8.3.5                    pypi_0    pypi
pytest-timeout            2.4.0                    pypi_0    pypi
python                    3.13.3          h2eb94d5_100_cp313  
python-dateutil           2.9.0post0      py313hca03da5_2  
python-dotenv             1.1.0                    pypi_0    pypi
python-fastjsonschema     2.20.0          py313hca03da5_0  
python-lsp-black          2.0.0           py313hca03da5_1  
python-lsp-jsonrpc        1.1.2              pyhd3eb1b0_0  
python-lsp-ruff           2.3.0           py313hca03da5_0  
python-lsp-server         1.13.1          py313h7eb115d_0  
python-slugify            5.0.2              pyhd3eb1b0_0  
python.app                3               py313h80987f9_2  
python_abi                3.13                    0_cp313  
pytimeparse               1.1.8                    pypi_0    pypi
pytokens                  0.2.0           py313hca03da5_0  
pytoolconfig              1.2.6           py313hca03da5_0  
pytz                      2025.2                   pypi_0    pypi
pyuca                     1.2             py313hca03da5_1  
pyyaml                    6.0.2           py313h80987f9_0  
pyzmq                     26.2.0          py313h313beb8_0  
qdarkstyle                3.2.3              pyhd3eb1b0_0  
qstylizer                 0.2.2           py313hca03da5_0  
qt-main                   5.15.2              h0917680_12  
qt-webengine              5.15.9               h2903aaf_7  
qtawesome                 1.4.0           py313hca03da5_0  
qtconsole                 5.7.0           py313hca03da5_0  
qtconsole-base            5.7.0              pyha770c72_0    conda-forge
qtpy                      2.4.1           py313hca03da5_0  
re2                       2024.07.02           h48ca7d4_0  
readline                  8.2                  h1a28f6b_0  
referencing               0.30.2          py313hca03da5_0  
reportlab                 4.4.4                    pypi_0    pypi
requests                  2.32.3          py313hca03da5_1  
requests-oauthlib         2.0.0                    pypi_0    pypi
roman-numerals-py         3.1.0           py313hca03da5_0  
rope                      1.13.0          py313hca03da5_0  
rpds-py                   0.22.3          py313h2aea54e_0  
rsa                       4.9.1                    pypi_0    pypi
rtree                     1.0.1           py313hca03da5_0  
ruff                      0.12.0          py313h59dbcda_0  
scipy                     1.15.2          py313h858dd5b_1  
scs                       3.2.7.post2              pypi_0    pypi
setuptools                72.1.0          py313hca03da5_0  
simplejson                3.20.2                   pypi_0    pypi
sip                       6.7.12          py313h313beb8_1  
six                       1.17.0                   pypi_0    pypi
smmap                     5.0.2                    pypi_0    pypi
snappy                    1.2.1                h313beb8_0  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.5             py313hca03da5_0  
sphinx                    8.2.3           py313h80987f9_0  
sphinxcontrib-applehelp   2.0.0              pyhd3eb1b0_1  
sphinxcontrib-devhelp     2.0.0              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.1.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      2.0.0              pyhd3eb1b0_1  
sphinxcontrib-serializinghtml 2.0.0              pyhd3eb1b0_0  
spyder                    6.1.0                hd8ed1ab_0    conda-forge
spyder-base               6.1.0           osx_pyh1a5313d_0    conda-forge
spyder-kernels            3.1.1           py313h7eb115d_0  
sqlite                    3.45.3               h80987f9_0  
stack_data                0.2.0              pyhd3eb1b0_0  
streamlit                 1.50.0                   pypi_0    pypi
streamlit-option-menu     0.4.0                    pypi_0    pypi
superqt                   0.7.3           py313h7eb115d_0  
tabulate                  0.9.0                    pypi_0    pypi
tenacity                  9.0.0           py313hca03da5_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
three-merge               0.1.1              pyhd3eb1b0_0  
thrift                    0.20.0                   pypi_0    pypi
tinycss2                  1.4.0           py313hca03da5_0  
tk                        8.6.14               h6ba3021_0  
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1           py313hca03da5_1  
tomlkit                   0.13.2          py313hca03da5_0  
tornado                   6.4.2           py313h80987f9_0  
traitlets                 5.14.3          py313hca03da5_0  
twelvedata                1.2.25                   pypi_0    pypi
typing-extensions         4.12.2          py313hca03da5_0  
typing_extensions         4.12.2          py313hca03da5_0  
tzdata                    2025.2                   pypi_0    pypi
ujson                     5.10.0          py313h313beb8_1  
ukkonen                   1.0.1           py313h48ca7d4_1  
unidecode                 1.3.8           py313hca03da5_0  
uritemplate               4.2.0                    pypi_0    pypi
urllib3                   2.4.0                    pypi_0    pypi
utf8proc                  2.6.1                h80987f9_1  
virtualenv                20.28.0         py313hca03da5_0  
watchdog                  4.0.2           py313h80987f9_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1           py313hca03da5_2  
whatthepatch              1.0.2           py313hca03da5_0  
wheel                     0.44.0          py313hca03da5_0  
wrapt                     1.17.0          py313h80987f9_0  
wurlitzer                 3.0.2           py313hca03da5_0  
xlrd                      2.0.2              pyhd3eb1b0_0  
xlsxwriter                3.2.3                    pypi_0    pypi
xlwings                   0.32.1          py313hca03da5_1  
xz                        5.6.4                h80987f9_1  
yaml                      0.2.5                h1a28f6b_0  
yapf                      0.40.2          py313hca03da5_0  
yarl                      1.18.0          py313h80987f9_0  
yfinance                  0.2.58                   pypi_0    pypi
zeromq                    4.3.5                h313beb8_0  
zipp                      3.21.0          py313hca03da5_0  
zlib                      1.2.13               hfb2fe0b_6    conda-forge
zstd                      1.5.6                hfb09047_0  

```
</details>

**Comment by ccordoba12** [comment]
Hey @andres-ytree, thanks for reporting and sorry for the late reply. I think this problem happens when there is an error starting a kernel for the environment Spyder is connected to.

After solving that problem, the error you reported should disappear. However, we'll take care of it so it doesn't annoy users in our next version (6.1.2), to be released in a couple of months.
