### ISSUE TITLE
Error when updating to 6.05: 'libmambapy' has no attribute 'QueryFormat'

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder#24058]
I've updated to 6.05 using the builtin updater of the standalone package on Ubuntu 24.04.

This error occured to me too after updating via the standalone installer:

```
Updating Spyder runtime environment...                                          
Traceback (most recent call last):                                              
  File "/home/user/.local/spyder-6/bin/mamba", line 7, in <module>             
    from mamba.mamba import main                                                
  File "/home/user/.local/spyder-6/lib/python3.11/site-packages/mamba/mamba.py", line 46, in <module>                                                          
    from mamba import repoquery as repoquery_api                                
  File "/home/user/.local/spyder-6/lib/python3.11/site-packages/mamba/repoquery.py", line 12, in <module>                                                      
    def _repoquery(query_type, q, pool, fmt=api.QueryFormat.JSON):              
                                            ^^^^^^^^^^^^^^^                     
AttributeError: module 'libmambapy' has no attribute 'QueryFormat'              
Cleaning packages and temporary files...                                        
Traceback (most recent call last):                                              
  File "/home/user/.local/spyder-6/bin/mamba", line 7, in <module>             
    from mamba.mamba import main                                                
  File "/home/user/.local/spyder-6/lib/python3.11/site-packages/mamba/mamba.py", line 46, in <module>
    from mamba import repoquery as repoquery_api
  File "/home/user/.local/spyder-6/lib/python3.11/site-packages/mamba/repoquery.py", line 12, in <module>
    def _repoquery(query_type, q, pool, fmt=api.QueryFormat.JSON):
                                            ^^^^^^^^^^^^^^^
AttributeError: module 'libmambapy' has no attribute 'QueryFormat'

```

when starting Spyder, the ipython console displays 

```
Traceback (most recent call last):
File "/home/user/.local/spyder𔂰/bin/mamba", line 7, in
from mamba.mamba import main
File "/home/user/.local/spyder𔂰/lib/python3.11/site‑packages/mamba/mamba.py", line 46, in
from mamba import repoquery as repoquery_api
File "/home/user/.local/spyder𔂰/lib/python3.11/site‑packages/mamba/repoquery.py", line 12, in
def _repoquery(query_type, q, pool, fmt=api.QueryFormat.JSON):
^^^^^^^^^^^^^^^
AttributeError: module 'libmambapy' has no attribute 'QueryFormat'
```

related: #24057

**Comment by ccordoba12** [comment]
Hey @skjerns, thanks for reporting and sorry for the inconvenience. This is a bug in the update process of our installers and we'll try to fix it as soon as possible.

In the meantime, I'm afraid the only solution is for you to remove your current installation and manually install 6.0.5.

**Comment by ccordoba12** [comment]
@mrclary, I think this problem was caused by the removal of the pinned Mamba version here:

https://github.com/spyder-ide/spyder/pull/24000/files#diff-999be8b88c185be2126c689283023243aec17ae0cbc32f780dbc05d16b1e553aL145

which changed the `conda-libmamba-solver` version that is compatible with conda 24.5.0 (the version we package in the base environment of our installers).

So, I think we should probably pin `libmambapy` to **1.5.8** and `conda-libmamba-solver` to **24.9.0** (the versions that came with 6.0.4) and regenerate the `conda-lock.zip` again.

**Comment by jeson-00** [comment]
Hi, I found the same issue on my PC. So the remaining solution is still to remove spyder and reinstall it manually?

**Comment by ccordoba12** [comment]
Yes, you need to uninstall Spyder manually and reinstall our latest version afterwards.
