### ISSUE TITLE
Open project error

### ISSUE THREAD

**Issue by alabd14313** [spyder-ide/spyder#4963]
Hello!
When I use "Project > Open project" to open an existing project, I have this error:

```python-traceback
  File "/usr/lib/python3.6/site-packages/spyder/plugins/projects.py", line 145, in <lambda>
    lambda v: self.editor.setup_open_files())
  File "/usr/lib/python3.6/site-packages/spyder/plugins/editor.py", line 2707, in setup_open_files
    filenames = self.reorder_filenames(filenames)
  File "/usr/lib/python3.6/site-packages/spyder/plugins/editor.py", line 2733, in reorder_filenames
    splitsettings = layout.get('splitsettings')
AttributeError: 'NoneType' object has no attribute 'get'
```

* Spyder Version: 4dev (master)
* Python Version: 3.6
* Qt Version: 5.9
* PyQt Version: 5.9
* Operating system: Arch Linux

**Comment by ccordoba12** [comment]
@rlaverde, I think this is related to the reordering of files in Projects you introduced in PR #4880.

**Comment by rlaverde** [comment]
I don't think It's related with my changes in #4880, instead It could be caused for a corrupted project configuration file, i.e. missing `layout_settings`
